
export const ProjectsData =  [
  {
    id: 0,
    title: "UIforest",
    description: "A design tool site offering free and premium Tailwind CSS components, built with Next.js, Shadcn UI, and advanced filtering/search capabilities.",
    image: "/uiforest.png",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/ake144/ui-forest",
    previewUrl: "https://uiforest.dev/",
  },
  {
    id: 1,
    title: "E-learning Platform",
    description: "A feature-rich e-learning web app allowing users to take quizzes, track progress, view stories, and improve learning. Built with Next.js 14, Node.js, nextauth, Prisma, and Tailwind CSS.",
    image: "/e-learning.png",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/ake144/E-LEARNING-FRONT",
    previewUrl: "https://brightethiopia.vercel.app/",
  },
  {
    id: 2,
    title: "Church platform",
    description: "A church platform to track attendance, register, and follow up memebers using QR-Scanner physical machine with generated Qr code",
    image: "/church1.png",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/ake144/attendance-with-QRCode",
    previewUrl: "https://www.brightethiopia.com/",
  },
  {
    id: 3,
    title: "CMS",
    description: "A modern CMS dashboard built with Next.js 14 and Prisma ORM. Features include content management, user and category statistics, and a professional UI using Shadcn component.",
    image: "/createPost.png",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/ake144/Nextjs_CMS",
    previewUrl: "https://nextjs-cms1.vercel.app/",
  },
  {
    id: 4,
    title: "HypoGo",
    description: "A site to maximize the productivity of students. It includes job searching, scholarships, AI tools, and other features.",
    image: "/home1.png",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/ake144/hypoGoo",
    previewUrl: "https://hypogo.vercel.app/",
  },
  {
    id: 5,
    title: "Tv network",
    description: "A TV network site built with Next.js and Material UI. It includes an admin panel to control programs and fetches data from a backend API.",
    image: "/mb.png",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/ake144/T-Movies",
    previewUrl: "https://tm-movie.vercel.app/",
  },
  {
    id: 6,
    title: "Crypto market",
    description: "Latest crypto market updates including real-time data on prices, market caps, and 24-hour changes.",
    image: "/crypto.jpg",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "https://crypto-info-xz8k.vercel.app/",
  },
  {
    id: 7,
    title: "Audio Transcription",
    description: "A user-friendly app to convert audio files into text using React, Next.js, and OpenAI APIs.",
    image: "/audio.png",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/ake144/next.js-transcription",
    previewUrl: "https://transcription-murex.vercel.app/",
  },
  {
    id: 8,
    title: "Church-platform",
    description: "A church platform to stay spiritually connected and access Bible stories, sermons, and events.",
    image: "/church.png",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/ake144/Church-platform",
    previewUrl: "https://apo-church.vercel.app/",
  },
  {
    id: 9,
    title: "WordPress site",
    description: "Custom WordPress site designed with Elementor, optimized for SEO and performance.",
    image: "/coinged.png",
    tag: ["All", "WordPress"],
    gitUrl: "/",
    previewUrl: "https://www.upwork.com/freelancers/aklilutamirate?p=1748312443210293248",
  },
];